export const GpsStationCodeMap: { [key: string]: string } = {
  babadan: 'BABA',
  bpptkg: 'BPTK',
  deles: 'DELS',
  grawah: 'GRWH',
  jrakah: 'JRKH',
  kendit: 'KNDT',
  klatakan: 'KLAT',
  labuhan: 'LABH',
  pasarbubar: 'PSBB',
  plawangan: 'PLAW',
  selo: 'SELO',
  puncak: 'PNCK',
  p1: 'P1',
}

export default [
  { value: 'babadan', text: 'Babadan' },
  { value: 'bpptkg', text: 'BPPTKG' },
  { value: 'deles', text: 'Deles' },
  { value: 'grawah', text: 'Grawah' },
  { value: 'jrakah', text: 'Jrakah' },
  { value: 'kendit', text: 'Kendit' },
  { value: 'klatakan', text: 'Klatakan' },
  { value: 'labuhan', text: 'Labuhan' },
  { value: 'pasarbubar', text: 'Pasarbubar' },
  { value: 'plawangan', text: 'Plawangan' },
  { value: 'selo', text: 'Selo' },
  { value: 'p1', text: '2km Depth' },
]
